name: CI pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v3

      - name: Setup Python
        usues: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        runs: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      - name: Run DVC pipeline
        runs: |
          # Directly run the DVC pipeline without pulling
          dvc repro