name: CI pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Ensure a stable version

      - name: Install dependencies
        run: |
          pip install --upgrade pip --no-cache-dir
          pip install -r requirements.txt --no-cache-dir
          pip install dvc dvc-s3 dvc-gdrive  # Install DVC + storage support

      - name: Configure DVC remote
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc remote modify origin auth basic
          dvc remote modify origin user $DAGSHUB_USERNAME
          dvc remote modify origin password $DAGSHUB_TOKEN

      - name: Pull data from DVC remote
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Check if the DVC remote is set up and pull data
          if dvc remote list | grep -q "origin"; then
            dvc pull
          else
            echo "No DVC remote configured, skipping pull."
          fi
          
      - name: Run DVC pipeline
        run: |
          dvc repro  # Run the pipeline

      - name: Run model tests
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python -m unittest discover -s tests -p "*.py"
